### ISSUE TITLE
Customizable speed-type directory

### ISSUE THREAD

**Issue by therockmandolinist** [parkouss/speed-type#1]
Hi there, it's good to see continued maintenance/improvement on this package. 

It'd be nice if the location of the `speed-type` directory was stored in a customizable variable. I think this is a good option to provide in general, though I would personally like it for compatibility with [tarsius/no-littering](https://github.com/tarsius/no-littering)

**Comment by parkouss** [comment]
Hi, thanks for raising this issue!
I think I just fixed that with https://github.com/parkouss/speed-type/commit/f87399c523a2d0c6c98549f507006f1313d9cd6c - feel free to reopen if I'm mistaken.
