### ISSUE TITLE
https access to gb not working

### ISSUE THREAD

**Issue by doolio** [parkouss/speed-type#3]
Firstly congratulations and thanks on taking over maintainer-ship of this package. I'm raising again an open issue namely hagleitn/speed-type#8 which is also mentioned under (closed) issue #2 here. @jasonm23 [workaround](https://github.com/hagleitn/speed-type/issues/8#issuecomment-239398477)  works but ideally we should be using https when available.

**Comment by jasonm23** [comment]
Actually, this works fine.  However you must compile emacs with gnutls, so that it can access https services.

The easy way around is the workaround you mentioned.

**Comment by jasonm23** [comment]
Can close this issue

**Comment by parkouss** [comment]
Thanks @jasonm23 for the hint - let's close this issue.
