### ISSUE TITLE
Close open issues from old project fixed in this project

### ISSUE THREAD

**Issue by doolio** [parkouss/speed-type#4]
It might be good practice to close any [open issues from the old/original project](https://github.com/hagleitn/speed-type/issues?q=is%3Aopen+is%3Aissue) that have now been fixed here with a closing statement to that effect.

**Comment by jasonm23** [comment]
Unfortunately this would be a waste of time, since we can't actually close Hagelin's issues

We could amend the README to state that the original package has been abandoned and place a new issue with a notice to that effect in the original repo issue.

**Comment by doolio** [comment]
Agreed.
