### ISSUE TITLE
A new official release to MELPA Stable?

### ISSUE THREAD

**Issue by doolio** [parkouss/speed-type#5]
Master branch is 10 commits ahead of release tagged as v1.0. Yet internally master branch is still labelled as v1.0. If you consider the master branch stable could you make a new official release (v1.1 say) to be available on MELPA Stable. 

I normally try to use MELPA Stable but wish to make use of your latest commits (e.g. the new var `speed-type-gb-dir`) and so have 'pinned' (using the feature in package.el) speed-type to MELPA but for some reason it continues to pull in your package from MELPA Stable - perhaps due to the same internal version numbering and how the MELPA recipes work. Thanks for your time.

**Comment by parkouss** [comment]
I've tagged the latest commit with 1.1, thanks for reminding me! It should be all good now, we just have to wait for the melpa build.
